# Generated by Django 4.1.3 on 2022-11-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0002_book_role_user_delete_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'orders_books',
                'managed': False,
            },
        ),
    ]
